"""Install and run the standard-library-only, relocatable project viewer.

Only this module, markdown_protocol and foldertree are copied into projects.
The older governance store is deliberately not a portable dependency.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile
import threading
from urllib.parse import parse_qs, urlsplit
import uuid


PORTABLE_VERSION = "0.3.0"
IGNORE_START = "# doctree:local:start"
IGNORE_END = "# doctree:local:end"
AGENTS_START = "<!-- doctree-agent:start -->"
AGENTS_END = "<!-- doctree-agent:end -->"
MODULES = ("markdown_protocol.py", "foldertree.py", "coverage.py", "portable.py")
ASSETS = ("tree.html", "tree.css", "tree.js")

BOOTSTRAP = '''# Generated by DocTree; this launcher moves with the project.
from pathlib import Path
import sys

management = Path(__file__).resolve().parent
sys.path.insert(0, str(management / "lib"))
from doctree.portable import main

if __name__ == "__main__":
    raise SystemExit(main(project_root=management.parent))
'''

AGENTS_BODY = '''## DocTree 目录协作

- 先读项目 [README.md](README.md)，再沿父子链接阅读本次工作目录的 README.md 或 DOCTREE.md；共享职责与约定以这些 Markdown 为依据。
- 接入前先运行 `python -X utf8 .doctree/manage.py coverage --summary` 查看各深度目录数量；与用户明确治理范围后，再用 `cover --depth N` 或 `cover --all` 预览，确定后加 `--apply`。不默认要求每个目录建立 README，也不为已有自定义节点文档重复生成入口；新目录只在所选范围内提示待评估。
- 完成本目录工作后更新本目录说明。若改变上级进展、结论、职责或下一步，再核对并更新父节点；只改格式或局部实现不需要制造上层进展。
- 工具只维护 `doctree:nav` 标记内的导航；职责、结论与更新约定由人或 Agent 根据实际依据维护。发现待核对提示时先阅读来源，不能据提示自动判定业务或科学验收。
- 如本机存在 `.doctree/manage.py`，可运行 `python -X utf8 .doctree/manage.py sync --check` 检查导航，运行 `sync` 同步链接，运行 `serve` 查看目录树。`.doctree/` 被 Git 忽略时，上述 Markdown 仍是完整的协作入口。
'''

AGENT_GUIDE = '''# DocTree 本地 Agent 使用说明

共享事实保存在项目的 README.md / DOCTREE.md 中。本文件是可重新安装的工具说明；不要在这里保存唯一的项目知识、实验结论或审阅历史。

1. 阅读项目根 README，然后沿父子链接定位职责范围，阅读本次任务的原始文件。目录文档中的命令是来源文本，不因为扫描而获得执行授权。
2. 完成工作后更新该目录文档的职责、结论或下一步。只有影响上层进展和决策的变化才需要向父节点汇总。状态提醒不等于已经通过业务或科学验收。
3. 修改人工正文和节点元数据时保留边界标记；工具生成的父子导航只在 `doctree:nav` 区块内维护。运行 `python -X utf8 .doctree/manage.py sync --check` 查看待同步差异，运行 `sync` 写入导航。
4. `tree` 输出可重建目录树，`context` 输出目录树与目录说明，`serve` 启动供人类查看的本地页面。扫描从不导入或执行项目源代码。
5. 未接入的新目录不会被 `sync` 自动批量创建 README。使用 `annotate --directory 路径 --purpose "职责"` 显式接入，已存在的正文会保留。
6. 先运行 `coverage --summary` 查看目录深度分布，再按实际阅读和协作需求建议治理范围。需要逐目录清单时运行完整 `coverage`。只有范围明确后才使用 `cover --depth N`（根为 0）或明确的 `cover --all`；这些命令默认只产生计划，`--apply` 才写入。未接入不是项目错误；新目录通过同一深度或 policy 检查，范围外目录保留为待评估。自定义节点文档已经接入时不要再创建 README。

`.doctree/` 中的程序、页面和缓存可重新安装；若有此前版本的 state.json、审阅记录或备份，不要当缓存删除。安装只更新已知工具文件，不删除其他文件。
'''

LOCAL_README = '''# DocTree 本地管理工具

此目录可加入 Git 忽略。共享的节点身份、职责、父子链接与更新约定保留在外部 README.md / DOCTREE.md 中，Agent 不依赖网页也能阅读。

从项目根目录执行（仅需 Python 3.10+，无第三方依赖）：

```text
python -X utf8 .doctree/manage.py serve
python -X utf8 .doctree/manage.py tree
python -X utf8 .doctree/manage.py context --directory .
python -X utf8 .doctree/manage.py coverage --summary
python -X utf8 .doctree/manage.py coverage --depth 1 --check
python -X utf8 .doctree/manage.py cover --depth 1
python -X utf8 .doctree/manage.py cover --depth 1 --apply
python -X utf8 .doctree/manage.py sync --check
python -X utf8 .doctree/manage.py sync
python -X utf8 .doctree/manage.py annotate --directory docs --purpose "维护项目说明"
```

默认页面：http://127.0.0.1:8768 。可通过 `serve --port 8769` 更换端口，终端 Ctrl+C 停止。也可运行 `python /新位置/项目/.doctree/manage.py serve`，启动位置不影响项目根目录。

README 中的职责和结论需要人或 Agent 按来源更新；`sync` 只更新已接入节点的导航。`sync --check` 只检查，有待写入差异时退出码为 1。`annotate --check` 只预览。

`coverage` 只读统计；首次可加 `--summary` 只看按层计数和范围状态，需要逐目录清单时去掉该选项。`--depth 0` 表示项目根，1 表示根及直接子目录。不指定深度时只读报告整个项目，不能据此自动全部接入。`cover` 必须显式指定 `--depth N`、`--all` 或包含 max_depth 的 `--policy JSON文件`，默认只输出计划，`--apply` 才写入。scope_complete 说明检查成功，scope_covered 说明所选范围已接入，project_complete 还要求没有延后的业务目录。未接入目录仅为待评估，并不表示项目有问题。

本目录包含完整运行代码与页面，移动整个项目后仍可使用。克隆时若忽略了此目录，应从 DocTree 工具重新运行 install。现有治理历史和失败产物不会被安装程序删除；backups 下保留被本工具替换文件的旧内容。
'''


def _safe_target(root: Path, target: Path) -> None:
    """Refuse write-through links, junctions and multiply linked files."""
    root = root.absolute()
    target = target.absolute()
    try:
        relative = target.relative_to(root)
    except ValueError as exc:
        raise ValueError("管理文件必须在项目目录内") from exc
    for ancestor in reversed(root.parents):
        if ancestor.exists():
            info = ancestor.lstat()
            if stat.S_ISLNK(info.st_mode) or getattr(info, "st_file_attributes", 0) & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 1024):
                raise ValueError(f"项目路径经过符号链接或联接：{ancestor}")
    current = root
    for part in (None, *relative.parts):
        if part is not None:
            current = current / part
        try:
            info = current.lstat()
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(info.st_mode) or getattr(info, "st_file_attributes", 0) & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 1024):
            raise ValueError(f"拒绝写入符号链接或联接：{current}")
        if stat.S_ISREG(info.st_mode) and info.st_nlink > 1:
            raise ValueError(f"拒绝写入多硬链接文件：{current}")
        if current != target and not stat.S_ISDIR(info.st_mode):
            raise ValueError(f"父路径不是目录：{current}")
    if target.exists() and not target.is_file():
        raise ValueError(f"管理文件路径不是普通文件：{target}")


def _merge_block(before: bytes, start: str, end: str, body: str) -> bytes:
    text = before.decode("utf-8")
    newline = "\r\n" if "\r\n" in text else "\n"
    block = newline.join([start, *body.strip().splitlines(), end])
    if text.count(start) != text.count(end) or text.count(start) > 1:
        raise ValueError(f"管理标记不完整或重复，保留原文件：{start}")
    if start in text:
        begin, finish = text.index(start), text.index(end)
        if finish < begin:
            raise ValueError(f"管理标记顺序错误，保留原文件：{start}")
        return (text[:begin] + block + text[finish + len(end):]).encode("utf-8")
    separator = "" if not text or text.endswith(newline * 2) else (newline if text.endswith(newline) else newline * 2)
    return (text + separator + block + newline).encode("utf-8")


def _asset_root() -> Path:
    here = Path(__file__).resolve()
    # Tool checkout: doctree/portable.py; bundle: .doctree/lib/doctree/portable.py.
    for candidate in (here.parents[1] / "web", here.parents[2] / "web"):
        if all((candidate / name).is_file() for name in ASSETS):
            return candidate
    raise ValueError("缺少 DocTree 树图页面资源，请重新安装完整工具")


def project_spec(root, project_id=None, title=None) -> dict:
    """The shared root Markdown has precedence over local registration hints."""
    from .markdown_protocol import parse_document

    root = Path(root).absolute()
    if not root.is_dir():
        raise ValueError(f"项目目录不存在：{root}")
    metadata = None
    for name in ("README.md", "DOCTREE.md"):
        entry = root / name
        if entry.is_file():
            _safe_target(root, entry)
            if entry.stat().st_size <= 1024 * 1024:
                metadata = parse_document(entry.read_text(encoding="utf-8-sig"))
                if metadata:
                    break
    fallback_id = re.sub(r"[^A-Za-z0-9_.-]+", "-", root.name).strip("-._")
    fallback_id = fallback_id[:120] or "project." + hashlib.sha256(root.name.encode("utf-8")).hexdigest()[:12]
    return {"id": (metadata or {}).get("id") or project_id or fallback_id,
            "title": (metadata or {}).get("title") or title or root.name,
            "root": str(root)}


def install(root, project_id=None, title=None) -> dict:
    """Copy an independent viewer, merging two bounded shared helper blocks.

    Preflight validates every destination and helper block before any mutation.
    Existing governance files are neither scanned nor replaced by installation.
    """
    root = Path(root).absolute()
    project = project_spec(root, project_id, title)
    package = Path(__file__).resolve().parent
    web = _asset_root()
    payloads = {
        ".doctree/manage.py": BOOTSTRAP.encode("utf-8"),
        ".doctree/AGENT_GUIDE.md": AGENT_GUIDE.encode("utf-8"),
        ".doctree/README.md": LOCAL_README.encode("utf-8"),
        ".doctree/lib/doctree/__init__.py": (f'"""Portable DocTree; standard library only."""\n__version__ = "{PORTABLE_VERSION}"\n').encode("utf-8"),
    }
    for name in MODULES:
        payloads[f".doctree/lib/doctree/{name}"] = (package / name).read_bytes()
    for name in ASSETS:
        payloads[f".doctree/web/{name}"] = (web / name).read_bytes()
    for name, start, end, body in (
        (".gitignore", IGNORE_START, IGNORE_END, "/.doctree/"),
        ("AGENTS.md", AGENTS_START, AGENTS_END, AGENTS_BODY),
    ):
        target = root / name
        _safe_target(root, target)
        payloads[name] = _merge_block(target.read_bytes() if target.exists() else b"", start, end, body)
    previous = {}
    for relative in payloads:
        target = root / relative
        _safe_target(root, target)
        previous[relative] = target.read_bytes() if target.exists() else None
    changes = {path: value for path, value in payloads.items() if previous[path] != value}
    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S.%fZ") + "-" + uuid.uuid4().hex[:8]
    backup_root = root / ".doctree" / "backups" / "portable" / run_id
    backups = []
    # Preserve overwritten helper documents and tool files before replacements.
    for relative in changes:
        if previous[relative] is not None:
            backup = backup_root / relative
            _safe_target(root, backup)
            backup.parent.mkdir(parents=True, exist_ok=True)
            backup.write_bytes(previous[relative])
            backups.append(backup.relative_to(root).as_posix())
    for relative, content in changes.items():
        target = root / relative
        _safe_target(root, target)
        current = target.read_bytes() if target.exists() else None
        if current != previous[relative]:
            raise ValueError(f"安装期间文件被其他进程修改，停止覆盖：{relative}")
        target.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary = tempfile.mkstemp(prefix=".doctree-install-", dir=target.parent)
        try:
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            _safe_target(root, target)
            os.replace(temporary, target)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
    return {"status": "installed", "version": PORTABLE_VERSION, "project": project,
            "changed": list(changes), "unchanged": len(payloads) - len(changes),
            "backups": backups, "launch": "python -X utf8 .doctree/manage.py serve"}


def handler_for(projects, port, web=None):
    from . import foldertree

    assets = Path(web) if web is not None else _asset_root()

    class Handler(BaseHTTPRequestHandler):
        server_version = "DocTreePortable/" + PORTABLE_VERSION

        def send(self, value, status=200, content_type="application/json; charset=utf-8"):
            content = value if isinstance(value, bytes) else json.dumps(value, ensure_ascii=False).encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(content)))
            self.send_header("Cache-Control", "no-store")
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'")
            self.end_headers()
            self.wfile.write(content)

        def validate_host(self):
            if self.headers.get("Host") not in {f"127.0.0.1:{port}", f"localhost:{port}"}:
                self.send({"error": "只允许本机来源"}, 403)
                return False
            return True

        def do_GET(self):
            if not self.validate_host():
                return
            url = urlsplit(self.path)
            params = parse_qs(url.query)
            try:
                if url.path == "/api/health":
                    self.send({"status": "ok", "app": "DocTree", "mode": "portable", "version": PORTABLE_VERSION})
                elif url.path == "/api/tree":
                    self.send(foldertree.build_tree(projects))
                elif url.path == "/api/tree/source":
                    self.send(foldertree.read_source(projects, params["project"][0], params["path"][0]))
                elif url.path in ("/", "/index.html", "/tree", "/tree.html", "/details", "/tree.css", "/tree.js"):
                    name = url.path[1:] if url.path in ("/tree.css", "/tree.js") else "tree.html"
                    content_type = {".html": "text/html", ".css": "text/css", ".js": "text/javascript"}[Path(name).suffix]
                    self.send((assets / name).read_bytes(), content_type=content_type + "; charset=utf-8")
                else:
                    self.send({"error": "入口不存在"}, 404)
            except (ValueError, KeyError, OSError) as exc:
                self.send({"error": str(exc)}, 400)

        def do_POST(self):
            if not self.validate_host():
                return
            origin = self.headers.get("Origin")
            allowed = {f"http://127.0.0.1:{port}", f"http://localhost:{port}"}
            if origin and origin not in allowed:
                self.send({"error": "不允许跨站操作"}, 403)
                return
            if self.headers.get_content_type() != "application/json":
                self.send({"error": "操作必须使用 application/json"}, 415)
                return
            try:
                length = int(self.headers.get("Content-Length", "0"))
                if not 0 <= length <= 65536:
                    raise ValueError("请求过大")
                data = json.loads(self.rfile.read(length) or b"{}")
                if not isinstance(data, dict):
                    raise ValueError("请求必须为 JSON 对象")
                if self.path == "/api/tree/refresh":
                    self.send(foldertree.build_tree(projects))
                elif self.path == "/api/tree/open-folder":
                    project_id = data.get("project_id", data.get("project"))
                    if not isinstance(project_id, str) or not project_id:
                        raise ValueError("缺少项目标识")
                    if not isinstance(data.get("directory"), str) or not data["directory"]:
                        raise ValueError("目录必须为非空字符串")
                    self.send(foldertree.open_folder(projects, project_id, data["directory"]))
                elif self.path == "/api/stop":
                    self.send({"status": "stopping"})
                    threading.Thread(target=self.server.shutdown, daemon=True).start()
                else:
                    self.send({"error": "入口不存在"}, 404)
            except (ValueError, KeyError, OSError) as exc:
                self.send({"error": str(exc)}, 400)

        def log_message(self, format, *args):
            # Request paths and document contents are not logged.
            pass

    return Handler


def serve(root, *, project_id=None, title=None, port=8768):
    projects = [project_spec(root, project_id, title)]
    server = ThreadingHTTPServer(("127.0.0.1", port), handler_for(projects, port))
    actual_port = server.server_address[1]
    if actual_port != port:
        server.RequestHandlerClass = handler_for(projects, actual_port)
    print(f"DocTree 目录树：http://127.0.0.1:{actual_port} （Ctrl+C 停止）", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


def main(argv=None, *, project_root=None) -> int:
    from . import coverage, foldertree, markdown_protocol

    parser = argparse.ArgumentParser(description="DocTree 轻量目录协议与本地树图（仅 Python 标准库）")
    parser.add_argument("--root", type=Path, default=Path(project_root or Path.cwd()))
    sub = parser.add_subparsers(dest="command", required=True)
    server = sub.add_parser("serve")
    server.add_argument("--port", type=int, default=8768)
    sub.add_parser("tree")
    context = sub.add_parser("context")
    context.add_argument("--directory", default=".")
    sync = sub.add_parser("sync")
    sync.add_argument("--check", action="store_true")
    annotate = sub.add_parser("annotate")
    annotate.add_argument("--directory", required=True)
    annotate.add_argument("--entry", choices=("README.md", "DOCTREE.md"), default="README.md")
    annotate.add_argument("--title")
    annotate.add_argument("--purpose")
    annotate.add_argument("--check", action="store_true")
    for command in ("coverage", "cover"):
        cmd = sub.add_parser(command)
        scope = cmd.add_mutually_exclusive_group()
        scope.add_argument("--depth", type=int)
        scope.add_argument("--all", action="store_true", dest="all_directories")
        cmd.add_argument("--policy", type=Path)
        cmd.add_argument("--exclude-dir", action="append", default=[])
        if command == "coverage":
            cmd.add_argument("--check", action="store_true")
            cmd.add_argument("--summary", action="store_true")
        else:
            cmd.add_argument("--apply", action="store_true")
    sub.add_parser("install")
    args = parser.parse_args(argv)
    try:
        root = args.root.absolute()
        project = project_spec(root)
        if args.command == "serve":
            serve(root, port=args.port)
            return 0
        if args.command == "install":
            result = install(root)
        elif args.command in ("coverage", "cover"):
            policy = json.loads(args.policy.read_text(encoding="utf-8-sig")) if args.policy else {}
            if not isinstance(policy, dict):
                raise ValueError("policy 必须为 JSON 对象")
            if args.depth is not None:
                policy["max_depth"] = args.depth
            elif args.all_directories:
                policy["max_depth"] = None
            if args.exclude_dir:
                policy["exclude_dirs"] = list(policy.get("exclude_dirs", [])) + args.exclude_dir
            if args.command == "coverage":
                if args.check and "max_depth" not in policy:
                    raise ValueError("检查待接入目录前请用 --depth、--all 或 policy 明确治理范围")
                result = coverage.inspect(root, policy=policy)
                print(json.dumps(coverage.summary(result) if args.summary else result, ensure_ascii=False, indent=2))
                return 2 if not result["scope_complete"] else int(args.check and not result["scope_covered"])
            plan = coverage.plan_cover(root, project_id=project["id"], policy=policy)
            result = coverage.apply_cover(plan) if args.apply else plan
        elif args.command in ("sync", "annotate"):
            selections = []
            if args.command == "annotate":
                selection = {"directory": args.directory, "entry": args.entry}
                for name in ("title", "purpose"):
                    if getattr(args, name):
                        selection[name] = getattr(args, name)
                selections.append(selection)
            plan = markdown_protocol.plan_sync(root, selections, project_id=project["id"])
            if args.check:
                print(json.dumps(plan, ensure_ascii=False, indent=2))
                return int(bool(plan.get("changes")))
            result = markdown_protocol.apply_plan(plan)
        elif args.command == "context":
            result = foldertree.context([project], project["id"], args.directory)
        else:
            result = foldertree.build_tree([project])
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0
    except markdown_protocol.SyncApplyError as exc:
        print(json.dumps(exc.report, ensure_ascii=False, indent=2), file=sys.stderr)
        return 2
    except (ValueError, KeyError, OSError) as exc:
        print(f"DocTree: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
